messages:

  # Сообщение, которое будет приходить игроку в при установке спавнера, если у него нет разрешения на установку спавнера
  # Плейсхолдеры: нет
  place_spawner_exception: "&cУ вас нет права ставить спавнер!"

  # Сообщение, которое будет приходить игроку в случае, если он неправильно ввел какую-либо команду
  # Плейсхолдеры: нет
  incorrect_parameters_exception: "&cВы неправильно ввели команду! &7(Попробуйте /spawners help)"

  # Сообщение, которое будет приходить игроку не имеющему разрешения выполнять какую-либо команду
  # Плейсхолдеры:
  # %command% - Меняется на команду, выполняемую игроком
  command_exception: "&cУ вас нет права на команду &6/%command%"

  # Сообщение, которое будет приходить игроку после выполнения команды /spawners reload
  # Плейсхолдеры: нет
  reload_command: "&6Плагин успешно перезагружен!"

  # Сообщение, которое будет приходить игроку после выполнения команды /spawners give.
  # Плейсхолдеры:
  # %item% - Меняется на название вида (моб_spawner)
  # %player% - Меняется на имя игрока.
  give_command: "&6Выдано &c%item% &6игроку &c%player% &6в количестве &c%number%&6!"

  # Сообщение, которое будет приходить игроку после выполнения команды /spawners set.
  # Плейсхолдеры:
  # %entity_type% - Менятеся на название моба, которого теперь будет содержать спавнер.
  set_command: "&6Моб успешно изменён на &c%entity_type%!"

  # Сообщение, которое будет приходить игроку, если он неправильно указал аргумент player. (/spawners give <player>)
  # Плейсхолдеры: нет
  invalid_player: "&cИгрок не найден!"

  # Сообщение, которое будет приходить игроку, если он неправильно указал аргумент entity_type. (/spawners set <entity_type)
  # Плейсхолдеры: нет
  invalid_entity: "&cТакого моба не существует!"

  # Сообщение, которое будет приходить игроку, если в его рабочем слоте не было спавнера в момент выполнения команды /spawners set
  # Плейсхолдеры: нет
  invalid_itemStack: "&cУ вас в руках нет спавнера!"

  # Сообщение, которое будет приходить игроку, если он неправильно указал аргумент material (/giveCustomPickaxe <material>)
  # Плейсхолдеры: нет
  invalid_type: "&cТакого инструмента не существует!"

  # Сообщение, которое будет приходить игроку, при вызове команду /spawners help
  # Плейсхолдеры: нет
  help_menu:
    - "&e---------- &6Помощь по плагину &5Spawners &e----------"
    - "&6/spawners reload &f- перезагружает плагин."
    - "&6/spawners give &2<Имя_игрока> <Имя_моба> <Количество> &f- Выдает спавнер мобов."
    - "&6/spawners set &2<Имя_моба> &f- Меняет моба в спавнере на другого."
    - "&6/getCustomPickaxe &2<Игрок> <Тип-инструмента> &f- Выдаёт игроку инструмент. "


pickaxe:
  display_name: "&5Супер-кирка"
  description:
    - "&6Даёт возможность получать в виде дропа"
    - "&6Любой &cрассадник мобов!"

# ----------Permissions---------- #
# 1) spawners.break - Если у игрока есть это право, то при ломании спавнера инструментом, выданным плагином, рассадник выпадет в виде дропа.
# 2) spawners.break.own - Если у игрока есть это право, то он сможет получить рассадник, сломая его своей киркой на шелковое касание.
# 3) spawners.place - Если у игрока есть это право, то он может устанавливать спавнеры.
# 4) spawners.spawners - Если у игрока есть это право, то игроку будут выводиться подсказки в чате (Если разрешаете хотя бы одну команду из /spawners, советую поставить).
# 5) spawners.spawners.reload - Если у игрока есть это право, то он может перезагружать плагин.
# 6) spawners.spawners.help - Если у игрока есть это право, то он может пользоваться командой /spawners help.
# 7) spawners.spawners.give - Если у игрока есть это право, то он может пользоваться командой /spawners give.
# 8) spawners.spawners.set - Если у игрока есть это право, то он может пользоваться командой /spawners set.
# 9) spawners.pickaxe - Если у игрока есть это право, то он может пользоваться командой /getCustomPickaxe.