name: Spawners
version: '${project.version}'
main: cold_ice_cube.spawners.Spawners
api-version: 1.14
authors: [ Cold_Ice_Cube ]
description: Плагин, добавляющий рассадникам мобов дополнительные функции.
website: https://github.com/Cold-Ice-Cube
commands:
  spawners:



